### ISSUE TITLE
Refactor `update_inspection` function to accommodate new schema `fertiscan_0.0.11`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#111]
## Description
The `update_inspection` function needs to be refactored to align with the new schema `fertiscan_0.0.11`.

## Tasks
- [ ] remove unnecessary schema specifications like `fertiscan_0.0.10` from the code
- [ ] bump schema version to `fertiscan_0.0.11` where necessary in the code
- [ ] integrate label_information new field `product_name`
- [ ] integrate label_information new field `warranty`
