### ISSUE TITLE
Integrate OLAP layer into `update_inspection`

### ISSUE THREAD

**Issue by Francois-Werbrouck** [ai-cfia/ailab-datastore#130]
## TODO

- [x] create trigger for deleted rows to remove themselves from the OLAP layer
- [x] create trigger for new row's ids to be insert into the OLAP layer
- [x] update the `new_inspection_function` to better suite the triggers
- [x] tests
