### ISSUE TITLE
As a dev, I want `build_inspection_export` and `build_inspection_import` to return a dict or model instead of a JSON string

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#211]
## Description

**Context**  
Currently, both `build_inspection_export` and `build_inspection_import` functions return a JSON string representation of an `Inspection` model. This appears to be designed to ease passing the data into SQL queries (check `new_inspection_with_label_info`). However, returning a JSON string leads to extra overhead in areas of the codebase that require converting this string back into a dictionary format to work with the `Inspection` data (tests & backend where the lib is used).

**Problem Statement**  
Returning the JSON string directly from these functions results in frequent and unnecessary conversions back to a dictionary in the code.

## Acceptance Criteria

- Refactor `build_inspection_export` and `build_inspection_import` to return a dictionary representation of the `Inspection` model or an object of type Inspection.
- Ensure query functions that require a JSON string perform the conversion from dictionary/model to JSON string locally.
- Verify that all current uses of `build_inspection_export` and `build_inspection_import` continue to function as expected with the dictionary output.

**Comment by k-allagbe** [comment]
@Francois-Werbrouck, thoughts?

**Comment by Francois-Werbrouck** [comment]
I wouldn't mind changing the type of the export since in the end we are passing the dict to the BE ( The BE should not directly call the import nor the export). 

However for the import, I'd leave it as a string since it is only used to send the the dict into the DB which requires it to be a str. Making it into a dict would only add additional steps when we use it since we need it to be a string. The returned value passed to the BE is the dict received from the DB once it has been saved (meaning it has ids). If you want the dict not to be a string, then I don't mind changing the type of the dict once received from the DB before returning it. 

Both instances are made to be used easily by our application. In the datastore we do not change the type multiple times, we just sticked to a JSON string. If changing the type of the dict helps other layers, lets switch it up. From my understanding the BE is changing the types of the dict, we could ease such operation by already returning the needed type.

**Comment by ChromaticPanic** [comment]
If we need multiple formats then could simply make new functions that return those formats?

**Comment by ChromaticPanic** [comment]
I would say to create both methods that return a dict and another one json if we need both. I agree that we should use prefer Model classes to pass data around in the backend.

**Comment by Francois-Werbrouck** [comment]
I don't see much value of updating the return type of the import. But here's a list of what needs to be updated to make this work.

## TODO

- [ ] Update the return type of 📦 `fertiscan.datastore.register_analysis()` for a model
- [ ] Update the return type of 📦 `fertiscan.datastore.get_full_inspection_json` for a model
- [ ] Update the return type of 📦 `fertiscan.datastore.update_inspection()` for a model
- [ ] Update the return type of 📦 `fertiscan.datastore.metadata.build_inspection_export()` for a model
- [ ] Update the return type of 📦 `fertiscan.datastore.metadata.build_inspection_import()` for a model
- [ ] Update  📦 `fertiscan.datastore.register_analysis()` to transform the model into a str JSON for the db to use
- [ ] Update  📦 `fertiscan.datastore.register_analysis()` to transform the result of the db into a model

**Comment by Francois-Werbrouck** [comment]
This was done in #229 we now use a model everywhere
