### ISSUE TITLE
few adjustments to conform the fertiscan schema to the architecture in `nachet-datastore`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#78]
## Description
Currently, the implemented fertiscan schema is not exactly conform to the design.

## Tasks
- [ ] create the schema when it doesn't exist?
- [ ] some tables are referenced before they exist
- [ ] some trigger functions still refer to `analysis` instead of `inspection`
- [ ] remove `owner_id` in `location` table in the schema
- [ ] remove `parent_picture_id` in `picture` in the architecture
- [ ] add `number` in `element_compound` in architecture
- [ ] remove `location` from `sample` in schema
- [ ] `content_fr` and `content_en` instead of `text_content..` in the schema?
- [ ] redesign the architecture as needed to allow creating and updating fertilizer inspection db entries

## Acceptance criteria
- the architecture satisfies the needs for creating and updating fertilizer inspection db entries
- the schema is conform to the design
