### ISSUE TITLE
Get User unfinished inspection

### ISSUE THREAD

**Issue by Francois-Werbrouck** [ai-cfia/ailab-datastore#96]
## Context

We have worked on the saving and updating of an label inspection. However, the user must be able to fetch his unfinished inspection to update them and verify them. 

## Prerequisites: 

- User must be registered and signed in

## TODO:
- [x] Create a high level function to recover an inspection in json based on its id.
- [x] Create a Label_Dimension table to recover the content faster
- [x] Update the insertion of inspection to Insert ids in the Label_Dimension table
- [x] Create a metadata module function to rebuild the JSON
- [x] Create a High level function to recover a list of unfinished inspection from a user_id

### Related issues on other layers:
https://github.com/ai-cfia/fertiscan-frontend/issues/178

**Comment by k-allagbe** [comment]
I suggest we do optimizations as a separate issue. Unless this is the optimization issue. In either case, we should focus on getting the basic features to work.
